:rotating_light: Fix beginBlockEvents type guard
The error was:
```
src/indexer.ts:117:24 - error TS2339: Property 'beginBlockEvents' does not exist on type 'never'.
117   return (blockResults.beginBlockEvents as BlockEvent37[]).filter(
                           ~~~~~~~~~~~~~~~~
Found 1 error in src/indexer.ts:117
```